Tox/tox.chat

index.html
<del>gonna add more</del>
Okay. If we can add links I would like "distributed" to be a link to some expanded explanation of the concept, and if that happens I'd like it to mention free/libre in the same way.
=> language tweaks

img/distributed.svg, index.html
Copy changes to match will come soon
=> merge p2p into distributed section, add distributed icon, swap p2p for freedom

index.html
=> actual content

index.html
=> Fix alignment issues with distributed.svg

css/style.css
=> transition button styles and add :active button style

LICENSE
=> Added CC-BY-SA License

src/about.html
=> Add new nav bar to About page

src/download.html
=> Increase font-size for the warning because it was hard to read

src/download.html
community repo packages on arch
=> closes #71

src/index.html
=> Fixed spelling error

src/download.html
Also I would suggest making this the general Android repo as it will most likely be used for any other clients that are added.
=> Change Antox fdroid repo

README.md, buildsite.py, src/download.html, src/index.html, tl/en.json
=> add buildsite.py for translations

src/about.html
We have received several emails from people saying that bylaws are 404. Maybe it's better to remove the link to bylaws until they are done?
=> Comment out bylaws link until bylaws are done

src/download.html
Latest build from here https://github.com/GrayHatter/uTox/releases
=> Update utox link to latest osx build

src/faq.html
we have similar link for Perfect forward secrecy so it would be fitting to have a link here too.
=> Added link to MITM attacks to FAQ

src/css/style.css
Appearance after changes
The complaint from #59
=> Simple fix for issue 59

themes/website/static/js/osdetect.js, themes/website/templates/clients.html, themes/website/templates/download.html
Less clicks => more happy users.
=> Adding links to the App Store for Antidote.

themes/website/static/js/osdetect.js, themes/website/templates/download.html
=> Added qTox download for OS X

themes/website/templates/index.html
That previous sentence was weirdly phrased
=> Improved wording on index page

themes/website/static/css/style.css, themes/website/templates/about.html
All this talk about The Tox Project 501(c)(3) organization and bylaws is
misleading, given no one is working on registering The Tox Project as an
501(c)(3) organization, nor anyone is working on bylaws.
=> Revise About page

themes/website/static/js/osdetect.js, themes/website/templates/download.html
@sudden6 @Diadlo It would be nice to get notified of when qTox links should be updated.
=> Update qTox OSX download

themes/website/static/js/osdetect.js, themes/website/templates/download.html
=> Update stable qTox Windows download links

themes/website/static/js/osdetect.js, themes/website/templates/download.html
=> Update uTox Windows download links

themes/website/static/js/osdetect.js, themes/website/templates/download.html
=> Update qTox OSX download link

themes/website/templates/clients.html
Add https://utox.io as uTox's website.
=> Add website address for uTox

themes/website/templates/clients.html
=> Update Ricin website

themes/website/templates/clients.html
=> Update qTox client description

themes/website/static/js/osdetect.js, themes/website/templates/download.html
Fixes https://github.com/Tox/tox.chat/issues/184.
=> Update qTox Windows download link

themes/website/static/js/osdetect.js, themes/website/templates/download.html
=> qTox version bump

themes/website/templates/download.html
JFreegman no longer maintains the groupbot
=> Remove groupbot reference

themes/website/templates/download.html
The Jenkins setup is not maintained actively anymore.
=> Switch qTox to Github hosted nightly builds

themes/website/static/js/osdetect.js, themes/website/templates/download.html
=> Update uTox Win download links

themes/website/templates/download.html
for C#, Objective-C/Swift, Python and Rust.
=> Remove links to unmaintained bindings

README.md
Based on the discussion in https://github.com/Tox/tox.chat/issues/224
=> Revise the TCS requirement

themes/website/static/js/osdetect.js, themes/website/templates/download.html
See: https://github.com/evilcorpltd/aTox/releases/tag/v0.6.0
=> Update aTox download links for v0.6.0

themes/website/static/js/osdetect.js, themes/website/templates/download.html
aTox is now available on [Google Play](https://play.google.com/store/apps/details?id=ltd.evilcorp.atox).
=> Link to aTox on Google Play

themes/website/templates/clients.html
Not sure how we want to do this. Just list uTox as unmaintained? Remove it entirely while no one is taking care of it?
=> Update uTox maintainer

themes/website/templates/clients.html
@tux3 @anthonybilinski @sudden6
Everyone fine with this?
=> Update qTox maintainer

themes/website/static/js/osdetect.js, themes/website/templates/download.html
Some groups claim they found a RCE in qTox, so we are removing download links to it for the abundance of caution.
=> Remove qTox download links

themes/website/templates/download.html
https://github.com/JFreegman/toxic/releases/tag/v0.13.1
=> Update toxic binary to 0.13.1

themes/website/templates/download.html
https://github.com/JFreegman/toxic/releases/tag/v0.14.1
=> Update toxic binary to version 0.14.1

themes/website/templates/clients.html
qTox was archived a year and half ago, let make it status clear.
=> Update clients.html regarding qTox status

themes/website/static/js/osdetect.js, themes/website/templates/download.html
=> Update aTox download links to v0.8.0

themes/website/static/js/osdetect.js, themes/website/templates/clients.html, themes/website/templates/download.html
This reverts commit 4b4970403a9e91d43b7d04736be9c260cb0508ef.
=> Revert "Remove qTox download links"
