src/download.html
Update repo instructions to clearly indicate which repositories are supported.
* We're currently being very misleading as to exactly which distributions are being supported
* The static builds for qtox are explicitly not being maintained - tux3 was quite clear on this point.
* Thinking the static packages will work well or even run at all is naive really, ABI compatibility between distributions is extremely poor. In general I would like to get rid of them completely - I'd rather we only provide *proper* pbuilder packages and the windows builds with their updaters.
* I'd rather not continue to tell people about the "release" codename for the same reasons
We're overstretching ourselves trying to pretend we support a lot more distributions than we actually can or have people to do. Also this …
=> Improve linux website instructions

src/about.html
The social media buttons on About page were different from all other pages, which shouldn't be the case.
=> Fix footer of About page

src/clients.html
Android support for qTox was only an experiment.
=> qTox doesn't support Android

themes/website/static/js/osdetect.js, themes/website/templates/download.html
Since we have recently removed .apk signing off Jenkins, the Antox .apk we link to is no longer signed, which causes issues https://github.com/Antox/Antox/issues/319. The .apk we have in our F-Droid repository is the same .apk as on Jenkins but signed, so we should link to that instead.
=> Changed Antox APK download URL

themes/website/static/js/osdetect.js, themes/website/templates/download.html
The provided versions are too old, the `uTox-0.7.0.dmg` link doesn't work and `uTox-0.4.2.dmg` sounds pre-historic.
=> Update uTox OS X download link

themes/website/static/css/style.css, themes/website/static/js/osdetect.js, themes/website/templates/download.html
Just a small update to keep the page up-to-date until the download page redesign is done.
- added link to [qTox's repository](https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox)
- added instructions for `stable` Debian/Ubuntu repository
- mentioned support of Xenial
- added qTox nightly download links (why not?)
- added Antox Google Play link
- fixed formatting a little, from `Client name 32 bit | 64 bit` and `Client name 32 bit | Client name 64 bit` to `Client name: 32 bit / 64 bit`
[I have temporary hosted the PR for you to test](http://198.46.138.44/).
=> Updated download page

themes/website/templates/clients.html
Some of client repositories were moved from their author's GitHub accounts to GitHub organizations.
=> Updated repository links of clients

themes/website/static/img/plat/plain.svg, themes/website/static/img/plat/plain_dark.svg, themes/website/static/img/plat/unknown_dark.svg, themes/website/templates/_base.html, themes/website/templates/download.html
Also added dark versions of plain.svg and unknown.svg as those icons looked alright as icon representing the developer section for now.
Fixes #130
=> Updated download-page to include a developer section. (issue #130)

themes/website/static/css/style.css
Images in the frontpage carousel no longer overlap or get cut off for some resolutions.
Fixes #134
=> Fixed carousel images getting cut off or overlapping.

themes/website/templates/about.html
When revising the about page in #142 I didn't remove "is" that was there before and apparently none of the PR reviewers have noticed this. I have checked all my changes against a spellchecker, but it obviously didn't catch that as it's not a spelling error. You all know that I'm typo master and I'm not the best at English, so please proof-read my PRs more thoughtfully.
This issue was pointed out by someone emailing us.
=> Fix typo on About page

pelicanconf.py, themes/website/static/css/style.css, themes/website/templates/_base.html
Replace license text with a GitHub link to the template file the page was generated from. The license icon still shows the license and it links to http://creativecommons.org/licenses/by-sa/4.0/, so the license text was more of a filler of sorts.
Before and after:
Inspired by https://about.gitlab.com/
=> Replace license text with GitHub page link

themes/website/templates/about.html
Some people seem to just eyeball the webpage for the email address without reading the text around it, which explicitly says not to use it for support questions.
=> Update contact information

themes/website/templates/clients.html
Add https://qtox.github.io as qTox's website.
=> Add website address for qTox

themes/website/templates/download.html
Mainly to change the
>Also, this is the Toxcore most clients currently use, although not for long, as most clients are in the process of switching to TokTok/c-toxcore.
part, since it's not accurate anymore, pretty much all clients now use TokTok/c-toxcore, aside from Toxygen.
=> Update and reword descriptions of toxcores

themes/website/templates/download.html
qTox uses the `-cmake` prefixed build jobs now.
Fixes #188.
=> Fix qTox nightly download links

themes/website/templates/_base.html
https://tox.chat/img/toxvert.png is HTTP 404, the correct path is https://tox.chat/theme/img/toxvert.png -- pelican quirks. I thought I have fixed all links then switching to Pelican, but apparently not.
=> Fix image path

themes/website/static/js/osdetect.js, themes/website/templates/download.html
I was planning on removing just the Debian/Ubuntu repository downloads, so that we could shutdown the package repository as per [the blog post](https://blog.tox.chat/2018/02/shutdown-of-the-debian-and-ubuntu-package-repository/), but apparently there were some more broken Linux downloads, so I have removed those too.
[The Gentoo overlay](https://github.com/Tox/gentoo-overlay-tox) and [the Arch repository](https://github.com/Tox/arch-repo-tox) are long unmaintained, in fact it even says so on the Download page
>Arch and Gentoo repos (not maintained)
so I have removed them. Generally toxcore and clients can be find in distribution's package repository, for example in Arch, Gentoo, openSUSE, PCLinuxOS, etc. (not Debian or Ubuntu yet though), so that's where the users should be looking at. …
=> Remove unmaintained downloads

themes/website/static/js/osdetect.js, themes/website/templates/download.html
We have decided to serve our release builds from Github releases from now on. Nightly builds stay on build.tox.chat in the near time.
=> link to Github for qTox releases

themes/website/templates/faq.html
In the light of the known vulnerabilities in the onion (see
https://github.com/TokTok/c-toxcore/issues/1152 ), I think we should
avoid claiming too much for it.
=> Remove strong claims for efficacy of the onion from the faq

themes/website/templates/clients.html
Since we already mention that uTox runs on Android (should we really mention that though?) I don't see why we shouldn't mention about Toxic being able to run on Android too.
=> Mention that Toxic can run on Android
